# Dockerfile — Servidor IoT Monitoring
# Imagen base mínima con GCC
FROM gcc:13-bookworm

WORKDIR /app

# Copiar fuente y compilar
COPY server.c .

RUN gcc -o server server.c -lpthread

# Crear carpeta de logs
RUN mkdir -p /app/logs

# Exponer el puerto por defecto
EXPOSE 9090

# Ejecutar: puerto 9090, logs en /app/logs/server.log
CMD ["./server", "9090", "/app/logs/server.log"]
